config/routes.rb
Bangarang::Application.routes.draw do
  root to: "welcomes#index"

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'requests' => redirect('http://dante.dev'), as: 'requests'

  resources :file_managers
  resources :movies do
    collection do
      get 'search'
      get 'forceupdate'
    end
  end
  resources :artists
  resources :albums do
    collection do
      get 'forceupdate'
    end
  end
  resources :servers do
    collection do
      get 'forceupdate'
      get 'status'
    end
  end
  resources :sessions
  resources :users do
    put :set_approved, on: :member
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.page(params[:page]).order(:title)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end

  # GET /movies/forceupdate
  def forceupdate
    Movie.update_movies

    @movies = Movie.all

    redirect_to movies_path, notice: 'Movies Updated.'
  end

  # GET /movies/search
  def search
    @search_results = Movie.search(params[:movie][:search])

    render 'index'
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.haml
= form_for @movie do |f|
  -if @movie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:"
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/movies/_search.html.haml
= form_tag search_movies_path, method: 'get', class: 'form-search' do
  = text_field :movie, :search, id: 'search_field', class: 'search-query'
  = submit_tag "Search", class: 'btn btn-primary'
  = link_to "Clear Search", movies_path, class: 'btn'

app/views/movies/edit.html.haml
%h1 Editing movie

= render 'form'

= link_to 'Show', @movie
\|
= link_to 'Back', movies_path

app/views/movies/index.html.haml
.container-fluid
	.row-fluid
		.span10
			%h1 Movies

			= render 'search'

			- if @search_results && @search_results.length == 0
				%h2 No results found.
			- elsif @search_results && @search_results.length > 0
				- @movies = @search_results

			- @movies.each do |movie|
				.row-fluid.well
					.span2
						= link_to movie do
							= image_tag movie.cover_url
					.span7
						%span.bigger= link_to movie.title, movie
						%br/
						- if movie.hd
							%span.label HD
							%span= " | "
						%span.big.gray= movie.director
						%p.big= movie.description
						%p= "Rating: #{movie.rating}/10"
						.progress.progress-success.progress-striped{style: 'width:100px'}
							.bar{style: "width:#{(Float(movie.rating) * 10).floor}%"}
					.span3
						%h2 Download
						- if !movie.definition.nil? && movie.definition.length > 0
							%p= movie.definition
							- movie.definition.split(",").each do |definition|
								- data = definition.split(":")
								= link_to data[0], "#{APP_CONFIG['ssh']['ssl_movies']}#{data[1]}", class: 'btn'
						- else
							= link_to 'Standard', '/download', class: 'btn'

	.row-fluid
		= will_paginate @movies
		- if current_user && current_user.admin
			= link_to 'Force Update', forceupdate_movies_path, class: 'btn'

app/views/movies/new.html.haml
%h1 New movie

= render 'form'

= link_to 'Back', movies_path

app/views/movies/show.html.haml
%p#notice= notice

= image_tag @movie.cover_url, width: 250

= link_to 'Back', movies_path