config/routes.rb
Bangarang::Application.routes.draw do
  root to: "welcomes#index"

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'requests' => redirect('http://dante.dev'), as: 'requests'

  resources :file_managers
  resources :movies do
    collection do
      get 'search'
      get 'forceupdate'
    end
  end
  resources :artists
  resources :albums do
    collection do
      get 'forceupdate'
    end
  end
  resources :servers do
    collection do
      get 'forceupdate'
      get 'status'
    end
  end
  resources :sessions
  resources :users do
    put :set_approved, on: :member
  end
end

app/models/server.rb
require 'net/ssh'

class Server < ActiveRecord::Base
	attr_accessible :domain, :ip, :hostname, :ip, :port
	attr_accessible :nickname, :username, :password, :is_media

	validates :domain, presence: true

	has_one :status
	has_many :status_data, through: :status
	has_many :disks

	def self.update_statuses
		puts "[LOG] Updating server statuses..."

		servers = Server.all

		servers.each do |server|
			server.status.up = (`if ping -q -c1 #{server} > /dev/null; then echo up; else echo down; fi`).chomp! == "up"

			server.ip = (`dig #{server} | grep -A 10 ';; ANSWER SECTION:' | grep -E '[[:space:]]+A[[:space:]]+' | awk '{ print $5; }'`).split("\n")[0]

			output = `nmap -p- #{server} | grep open`
			ports = output.gsub(/^(.*)open\ (.*)$/, '\1\2').split("\n")#.gsub(/([0-9]+)\/.*$/, '\1').split("\n")

			server.status.ports_open = ports.length
			server.status.ports = ports.join(',')

			begin
				Net::SSH.start(server.to_s, server.username, password: server.password, port: server.port, timeout: 5) do |ssh|
					stdout = ""

					ssh.exec!("uptime") do |channel, stream, data|
						stdout << data if stream == :stdout
					end
					if stdout.include?('day') || stdout.include?('days')
						if stdout.include?('min')
							data = stdout.gsub(/^.*up\s+(\d+)\s+days?,\s+(\d+)\s+min,\s+(\d+)\s+users?,\s+load\ average:\ ([\d.]+),\ ([\d.]+),\ ([\d.]+).*$/, '\1:\2:\3:\4:\5:\6:\7')

							data = data.split(":")
							server.status.uptime = "#{data[0]}:#{data[1]}:0"
							user_count = Integer(data[2])
							last_minute_load = Integer(Float(data[3]) * 100)
							last_five_load = Integer(Float(data[4]) * 100)
							last_fifteen_load = Integer(Float(data[5]) * 100)
						else
							data = stdout.gsub(/^.*up\s+(\d+)\s+days?,\s+(\d+):(\d+),\s+(\d+)\s+users?,\s+load\ average:\ ([\d.]+),\ ([\d.]+),\ ([\d.]+).*$/, '\1:\2:\3:\4:\5:\6:\7')

							data = data.split(":")
							server.status.uptime = "#{data[0]}:#{data[1]}:#{data[2]}"
							user_count = Integer(data[3])
							last_minute_load = Integer(Float(data[4]) * 100)
							last_five_load = Integer(Float(data[5]) * 100)
							last_fifteen_load = Integer(Float(data[6]) * 100)
						end
					else
						data = stdout.gsub(/^.*up\s+(\d+):(\d+),\s+(\d+)\s+users?,\s+load\ average:\ ([\d.]+),\ ([\d.]+),\ ([\d.]+).*$/, '\1:\2:\3:\4:\5:\6:\7')

						data = data.split(":")
						server.status.uptime = "0:#{data[0]}:#{data[1]}"
						user_count = Integer(data[2])
						last_minute_load = Integer(Float(data[3]) * 100)
						last_five_load = Integer(Float(data[4]) * 100)
						last_fifteen_load = Integer(Float(data[5]) * 100)
					end

					stdout = ""

					ssh.exec!("free -m | grep Mem: | awk '{ print $2,$3,$4; }'") do |channel, stream, data|
						stdout << data if stream == :stdout
					end

					data = stdout.split(" ")

					total_memory = Integer(data[0])
					used_memory = Integer(data[1])
					free_memory = Integer(data[2])

					server.status.status_data.create(user_count: user_count,
						last_minute_load: last_minute_load,
						last_five_load: last_five_load,
						last_fifteen_load: last_fifteen_load,
						total_memory: total_memory,
						free_memory: free_memory,
						used_memory: used_memory)

					stdout = ""

					ssh.exec!("ip addr | grep -A 1 eth0 | awk '{ print $2; }' | tail -n 3") do |channel, stream, data|
						stdout << data if stream == :stdout
					end

					data = stdout.split("\n")

					server.status.mac_address = data[0]
					server.status.ip = data[1]
					server.status.ip6 = data[2]

					server.disks.delete_all

					stdout = ""

					ssh.exec!("df -h | grep sd") do |channel, stream, data|
						stdout << data if stream == :stdout
					end

					puts stdout

					stdout.split("\n").each do |datum|
						info = datum.gsub(/^(.+?)\s+(.+?)\s+(.+?)\s+(.+?)\s+(\d+)%\s+(.+?)\s*$/, '\1:\2:\3:\4:\5:\6')
						data = info.split(':')

						server.disks.create(
							name: data[0], size: data[1], space_used: data[2],
							space_available: data[3], percent_used: Integer(data[4]),
							mount_point: data[5]
						)
					end
				end
			rescue Exception => e
				puts "[LOG] Could not SSH into #{server} (error: #{e.message})"
			end

			server.save
			server.status.save

			puts "[LOG] #{server} updated."
		end

		puts "[LOG] Update complete."
	end

	def is_media?
		self.is_media
	end

	def user
		if self.username
			self.username
		else
			APP_CONFIG['ssh']['username']
		end
	end

	def pass
		if self.password
			self.password
		else
			APP_CONFIG['ssh']['password']
		end
	end

	def to_s
		if self.hostname.length > 0
			self.hostname + "." + self.domain
		else
			self.domain
		end
	end

	def display_name
		if self.nickname
			"#{self.nickname} (#{self})"
		else
			self
		end
	end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :ensure_admin

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])
    minute_data = []
    five_data = []
    fifteen_data = []
    users_data = []
    used_memory_data = []
    free_memory_data = []

    if @server.status
      @server.status.status_data.each do |datum|
        minute_data << datum.last_minute_load
        five_data << datum.last_five_load
        fifteen_data << datum.last_fifteen_load
        users_data << datum.user_count
        used_memory_data << datum.used_memory
        free_memory_data << datum.free_memory
      end
    end

    @minute_load = minute_data.join(",")
    @five_load = five_data.join(",")
    @fifteen_load = fifteen_data.join(",")
    @users_load = users_data.join(",")
    @used_memory_data = used_memory_data.map { |d| d.nil? ? 0 : d }.join(",")
    @free_memory_data = free_memory_data.map { |d| d.nil? ? 0 : d }.join(",")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])
    @server.create_status(up: false, ports_open: 0, ports: '')

    respond_to do |format|
      if @server.save
        Server.update_statuses

        format.html { redirect_to servers_path, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to servers_path, notice: 'Server was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :ok }
    end
  end

  # GET /servers/status
  def status
    @servers = Server.all
  end

  # GET /servers/forceupdate
  def forceupdate
    Server.update_statuses

    @servers = Server.all

    redirect_to status_servers_path, notice: 'Server statuses updated.'
  end

  private

  def ensure_admin
    unless current_user && current_user.admin
      redirect_to login_path
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.haml
= form_for @server do |f|
  - if @server.errors.any?
    .alert.alert-block.alert-error.fade.in
      = link_to raw('&times;'), '#', class: 'close', "data-dismiss" => 'alert'
      %h4.alert-heading= "#{pluralize(@server.errors.count, "error")} prohibited this server from being saved:"
      %ul
        - @server.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :hostname
    = f.text_field :hostname
  .field
    = f.label :domain
    = f.text_field :domain
  .field
    = f.label :port
    = f.text_field :port
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :is_media, 'Media Server'
    = f.check_box :is_media
  .actions
    = f.submit 'Update Server', class: 'btn btn-primary'

app/views/servers/edit.html.haml
%h1 Editing server

= render 'form'

= link_to 'Delete Server', @server, class: 'btn', confirm: 'Are you sure?', method: :delete
= link_to 'Back', servers_path, class: 'btn'

app/views/servers/index.html.haml
%h1 Manage Servers

- @servers.each do |server|
	%p.pad
		- if server.nickname.nil? || server.nickname.length == 0
			= link_to server, edit_server_path(server), class: 'big'
		- else
			= link_to "#{server.nickname}", edit_server_path(server), class: 'big'
			%br
			%span.gray= server
		%br
		%span.gray= server.ip

= link_to 'Add Server', new_server_path, class: 'btn'

app/views/servers/new.html.haml
%h1 New server

= render 'form'

= link_to 'Back', servers_path, class: 'btn'

app/views/servers/show.html.haml
%h1= @server.display_name
%p.gray= @server.ip

- if @server.status
	%p.big= "Uptime: #{@server.status.uptime_tos}"
- else
	%p.big Uptime: unknown

.row-fluid
	.span4
		#load-container
	.span4
		#users-container
	.span4
		#memory-container

%script
	window.App = window.App || {};
	window.App.Data = window.App.Data || {};
	= "window.App.Data.minute_data = [#{@minute_load}];"
	= "window.App.Data.five_data = [#{@five_load}];"
	= "window.App.Data.fifteen_data = [#{@fifteen_load}];"
	= "window.App.Data.users_data = [#{@users_load}];"
	= "window.App.Data.used_memory_data = [#{@used_memory_data}];"
	= "window.App.Data.free_memory_data = [#{@free_memory_data}];"

%h3 eth0
%p= "MAC: #{@server.status.mac_address}"
%p= "IPv4: #{@server.status.ip}"
%p= "IPv6: #{@server.status.ip6}"

- if @server.disks.present?
	%h3 Disks
	%table.table.table-bordered.table-striped
		%tr
			%th Name
			%th Mount Point
			%th Size
			%th Used
			%th Free
			%th Percentage
		- @server.disks.each do |disk|
			%tr
				%td= disk.name
				%td= disk.mount_point
				%td= disk.size
				%td= disk.space_used
				%td= "#{disk.space_available} (#{100 - disk.percent_used}% free)"
				%td
					.progress
						- if disk.percent_used < 80
							.bar.bar-success{style: "width:#{disk.percent_used}%"}
						- elsif disk.percent_used < 90
							.bar.bar-warning{style: "width:#{disk.percent_used}%"}
						- else
							.bar.bar-danger{style: "width:#{disk.percent_used}%"}

%h3= "Ports (#{@server.status.ports_open} Open)"
- unless @server.status.ports_open == 0
	%table.table.table-striped.table-condensed.table-bordered
		%thead
			%tr
				%th Port
				%th Protocol
				%th Service
		%tbody
			- @server.status.ports.split(',').each do |port|
				%tr
					- p = port.split("/"); a = p[1].split(" ")
					%td= p[0]
					%td= a[0]
					%td= a[1]

= link_to 'Back', status_servers_path, class: 'btn'

app/views/servers/status.html.haml
%h1 Server Status

.span4
	- flash.each do |key, value|
		.alert.alert-block.alert-info.fade.in
			= link_to raw('&times;'), '#', class: 'close', "data-dismiss" => 'alert'
			%h4.alert-heading Information
			%span= value
	%table.table.table-striped.table-bordered
		%thead
			%tr
				%th Server
				%th Status
		%tbody
			- @servers.each do |server|
				%tr
					%td
						- if !server.nickname.nil? && server.nickname.length > 0
							= link_to "#{server.nickname}", server, class: 'big'
							%br
							%span.gray= "(#{server})"
						- else
							= link_to "#{server}", server, class: 'big'
					- if server.status
						%td{class: "#{server.status.up ? "green" : "red"}"}= server.status.up ? "Up" : "Down"
					- else
						%td{class: 'red'} Down
	= link_to 'Force Update', forceupdate_servers_path, class: 'btn', id: 'status_forceupdate'