config/routes.rb
Bangarang::Application.routes.draw do
  root to: "welcomes#index"

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'requests' => redirect('http://dante.dev'), as: 'requests'

  resources :file_managers
  resources :movies do
    collection do
      get 'search'
      get 'forceupdate'
    end
  end
  resources :artists
  resources :albums do
    collection do
      get 'forceupdate'
    end
  end
  resources :servers do
    collection do
      get 'forceupdate'
      get 'status'
    end
  end
  resources :sessions
  resources :users do
    put :set_approved, on: :member
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	validates :password, :password_confirmation, presence: true, if: :admin?
	validates :username, presence: true, uniqueness: true, format: { with: /^[a-z0-9_\-@\.]*$/i }
	validates :email, presence: true, format: { with: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

	attr_accessible :name, :password, :password_confirmation, :username, :email, :approved, :admin
	has_secure_password

	private

	def admin?
		defined? current_user && (!current_user || !current_user.admin)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in, except: [:new, :create]
  before_filter :ensure_admin, only: [:manage, :set_approved]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /manage
  def manage
    @users = User.all

    respond_to do |format|
      format.html # approved.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html do
          if current_user && current_user.admin
            redirect_to users_path, notice: 'User created.'
          else
            redirect_to root_path, notice: "An email has been sent to the administrator for review and addition."
          end
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_approved
    @user = User.find(params[:id])
    @user.approved = true
    puts 'saving...'
    if @user.save
      puts 'success'
    else
      puts 'failure'
    end
    puts 'saved?'

    respond_to do |format|
      format.js
    end

    # Call program
    #if system('/users/jsvana/bang add', @user.username, @user.password)
    #  puts 'Added'
    #else
    #  puts 'failure'
    #end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  private

  def ensure_logged_in
    unless current_user
      redirect_to login_path
    end
  end

  def ensure_admin
    unless current_user && current_user.admin
      redirect_to login_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user, html: { class: 'form-horizontal' } ) do |f|
  - if @user.errors.any?
    .alert.alert-block.alert-error.fade.in
      = link_to raw('&times;'), '#', class: 'close', "data-dismiss" => 'alert'
      %h4.alert-heading= "#{pluralize(@user.errors.count, "error")} prohibited this server from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation, 'Confirm Password'
    = f.password_field :password_confirmation
  .field
    = f.label :email
    = f.email_field :email
  - if current_user && current_user.admin
    .field
      = f.label :approved, class: 'checkbox' do
        = f.check_box :approved
        Approved
    .field
      = f.label :admin, class: 'checkbox' do
        = f.check_box :admin
        Admin
  .actions
    /%br/
    = f.submit class: 'btn-primary'

app/views/users/edit.html.haml
%h1
	Account Settings for 
	= @user.username

.span4.well
	= render 'form'

	- unless @user == current_user
		= link_to 'Delete User', @user, class: 'btn', confirm: 'Are you sure?', method: :delete
	- if current_user.admin
		= link_to 'Back', users_path, class: 'btn'
	- else
		= link_to 'Back', root_path, class: 'btn'

app/views/users/index.html.haml
.span3
	%h1 Manage Users

	- @users.each do |user|
		= div_for user do
			%p.pad
				= link_to user.username, edit_user_path(user)
				- if user.approved
					%span.right Approved
				- else
					= link_to "Approve", set_approved_user_path(user), class: 'btn right', id: "#{user.id}_link", method: :put, remote: true
	
	= link_to 'New User', new_user_path, class: 'btn'

app/views/users/manage.html.haml
.span4
	%h1 Users

	- @users.each do |user|
		= div_for user do
			%p.pad
				= link_to user.username, user
				- if user.approved
					%span.right Approved
				- else
					= link_to "Approve", set_approved_user_path(user), class: 'btn right', id: "#{user.id}_link", method: :put, remote: true

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path, class: 'btn'

app/views/users/set_approved.js.erb
$('<span class="right">Approved</span>').insertAfter('#<%= @user.id %>_link').effect('highlight');
$('#<%= @user.id %>_link').remove();

app/views/users/show.html.haml
%p#notice
  = notice

%p
  %b Name:
  %span= @user.name
%p
  %b Username:
  %span= @user.username
%p
  %b Password:
  %span [Filtered]
%p
  %b Email:
  %span= @user.email

= link_to 'Edit', edit_user_path(@user), class: 'btn'
%span |
- if current_user.admin
  = link_to 'Back', users_path, class: 'btn'
- else
  = link_to 'Back', root_path, class: 'btn'