config/routes.rb
Bangarang::Application.routes.draw do
  root to: "welcomes#index"

  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'requests' => redirect('http://dante.dev'), as: 'requests'

  resources :file_managers
  resources :movies do
    collection do
      get 'search'
      get 'forceupdate'
    end
  end
  resources :artists
  resources :albums do
    collection do
      get 'forceupdate'
    end
  end
  resources :servers do
    collection do
      get 'forceupdate'
      get 'status'
    end
  end
  resources :sessions
  resources :users do
    put :set_approved, on: :member
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title= content_for?(:title) ? yield(:title) : APP_CONFIG['title']
		= stylesheet_link_tag "application"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		-#.navbar.navbar-fixed-top
		-#	.navbar-inner
		-#		.container-fluid
		-#			%a.btn.btn-navbar{data: {toggle: "collapse", target: ".nav-collapse"}}
		-#				%span.icon-bar
		-#				%span.icon-bar
		-#				%span.icon-bar
		-#			%a.brand{href: "#"} Project name
		-#			.nav-collapse
		-#				%ul.nav
		-#					%li.active
		-#						%a{href: "#"} Home
		-#					%li
		-#						%a{href: "#about"} About
		-#					%li
		-#						%a{href: "#contact"} Contact
		-#				%p.navbar-text.pull-right
		-#					Logged in as
		-#					%a{href: "#"} username

		.container-fluid
			.row-fluid
				.span12
					%header#header
						= link_to root_path, title: 'Home' do
							= image_tag "logo.png", width: 700

			%hr

			.row-fluid
				.span2
					.well.sidebar-nav
						%ul.nav.nav-list
							- if current_user
								%p= "Welcome, #{current_user.username}."
								%li.nav-header MEDIA
								%li= link_to 'Music', albums_path
								%li= link_to 'Movies', movies_path
								%li= link_to 'TV', '/tv'
								%li= link_to 'Games', '/games'
								%li= link_to 'Request', requests_path
								- if current_user.admin
									%li.nav-header ADMIN
									%li= link_to 'Server Status', status_servers_path
									%li= link_to 'Manage Servers', servers_path
									%li= link_to 'Manage Users', users_path
									%li= link_to 'Manage Files', file_managers_path
								%li.nav-header META
								%li= link_to 'Home', root_path
								%li= link_to 'Account Settings', edit_user_path(current_user)
								%li= link_to 'Logout', logout_path
							- else
								%li.nav-header META
								%li= link_to 'Home', root_path
								%li= link_to 'Login', login_path
				.span10
					.content
						= yield
			%hr

			%footer
				%p.center
					= raw("&copy; #{APP_CONFIG['network_name']}")
					= Date.today.year

app/views/layouts/login.html.haml
!!! 5
%html
	%head
		%title= content_for?(:title) ? yield(:title) : APP_CONFIG['title']
		= stylesheet_link_tag "application"
		= stylesheet_link_tag "bootstrap"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		.content
			= yield